In [24]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [25]:
dataset = pd.read_csv('/Users/alvina/Desktop/GERMAN-CREDIT-PROCESSOR/https:/github.com/datagirl01/german-credit-processor/data/raw/german_credit.csv')

In [26]:
dataset.head()

,Creditability,Account Balance,Duration of Credit (month),Payment Status of Previous Credit,Purpose,Credit Amount,Value Savings/Stocks,Length of current employment,Instalment per cent,Sex & Marital Status,Guarantors,Duration in Current address,Most valuable available asset,Age (years),Concurrent Credits,Type of apartment,No of Credits at this Bank,Occupation,No of dependents,Telephone,Foreign Worker
0,1,1,18,4,2,1049,1,2,4,2,1,4,2,21,3,1,1,3,1,1,1
1,1,1,9,4,0,2799,1,3,2,3,1,2,1,36,3,1,2,3,2,1,1
2,1,2,12,2,9,841,2,4,2,2,1,4,1,23,3,1,1,2,1,1,1
3,1,1,12,4,0,2122,1,3,3,3,1,2,1,39,3,1,2,2,2,1,2
4,1,1,12,4,0,2171,1,3,4,3,1,4,2,38,1,2,2,2,1,1,2

In [28]:
print("Label => Creditability")
print("Attributes => {}".format(dataset[1:].columns))

Label => Creditability
Attributes => Index(['Creditability', 'Account Balance', 'Duration of Credit (month)',
       'Payment Status of Previous Credit', 'Purpose', 'Credit Amount',
       'Value Savings/Stocks', 'Length of current employment',
       'Instalment per cent', 'Sex & Marital Status', 'Guarantors',
       'Duration in Current address', 'Most valuable available asset',
       'Age (years)', 'Concurrent Credits', 'Type of apartment',
       'No of Credits at this Bank', 'Occupation', 'No of dependents',
       'Telephone', 'Foreign Worker'],
      dtype='object')

In [29]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
Creditability                        1000 non-null int64
Account Balance                      1000 non-null int64
Duration of Credit (month)           1000 non-null int64
Payment Status of Previous Credit    1000 non-null int64
Purpose                              1000 non-null int64
Credit Amount                        1000 non-null int64
Value Savings/Stocks                 1000 non-null int64
Length of current employment         1000 non-null int64
Instalment per cent                  1000 non-null int64
Sex & Marital Status                 1000 non-null int64
Guarantors                           1000 non-null int64
Duration in Current address          1000 non-null int64
Most valuable available asset        1000 non-null int64
Age (years)                          1000 non-null int64
Concurrent Credits                   1000 non-null int64
Type of apartment                    1000 non-null int64
No of Credits at this Bank           1000 non-null int64
Occupation                           1000 non-null int64
No of dependents                     1000 non-null int64
Telephone                            1000 non-null int64
Foreign Worker                       1000 non-null int64
dtypes: int64(21)
memory usage: 164.1 KB

In [34]:
print("Count of positive samples: ",len(dataset[dataset['Creditability']==1]))
print("Count of positive samples: ",len(dataset[dataset['Creditability']==0]))

Count of positive samples:  700
Count of positive samples:  300

### Drop colums considering correlation

In [276]:
dataset.columns

Index(['Creditability', 'Account Balance', 'Duration of Credit (month)',
       'Payment Status of Previous Credit', 'Purpose', 'Credit Amount',
       'Value Savings/Stocks', 'Length of current employment',
       'Instalment per cent', 'Sex & Marital Status', 'Guarantors',
       'Duration in Current address', 'Most valuable available asset',
       'Age (years)', 'Concurrent Credits', 'Type of apartment',
       'No of Credits at this Bank', 'Occupation', 'No of dependents',
       'Telephone', 'Foreign Worker'],
      dtype='object')

In [562]:
datasetNew = dataset.drop('Telephone',axis=1)
datasetNew = datasetNew.drop('Duration in Current address',axis=1)
datasetNew = datasetNew.drop('No of dependents',axis=1)
datasetNew

,Creditability,Account Balance,Duration of Credit (month),Payment Status of Previous Credit,Purpose,Credit Amount,Value Savings/Stocks,Length of current employment,Instalment per cent,Sex & Marital Status,Guarantors,Most valuable available asset,Age (years),Concurrent Credits,Type of apartment,No of Credits at this Bank,Occupation,Foreign Worker
0,1,1,18,4,2,1049,1,2,4,2,1,2,21,3,1,1,3,1
1,1,1,9,4,0,2799,1,3,2,3,1,1,36,3,1,2,3,1
2,1,2,12,2,9,841,2,4,2,2,1,1,23,3,1,1,2,1
3,1,1,12,4,0,2122,1,3,3,3,1,1,39,3,1,2,2,2
4,1,1,12,4,0,2171,1,3,4,3,1,2,38,1,2,2,2,2
5,1,1,10,4,0,2241,1,2,1,3,1,1,48,3,1,2,2,2
6,1,1,8,4,0,3398,1,4,1,3,1,1,39,3,2,2,2,2
7,1,1,6,4,0,1361,1,2,2,3,1,1,40,3,2,1,2,2
8,1,4,18,4,3,1098,1,1,4,2,1,3,65,3,2,2,1,1
9,1,2,24,2,3,3758,3,1,1,2,1,4,23,3,1,1,1,1
10,1,1,11,4,0,3905,1,3,2,3,1,1,36,3,1,2,3,1
11,1,1,30,4,1,6187,2,4,1,4,1,3,24,3,1,2,3,1
12,1,1,6,4,3,1957,1,4,1,2,1,3,31,3,2,1,3,1
13,1,2,48,3,10,7582,2,1,2,3,1,4,31,3,2,1,4,1
14,1,1,18,2,3,1936,5,4,2,4,1,3,23,3,1,2,2,1
15,1,1,6,2,3,2647,3,3,2,3,1,1,44,3,1,1,3,1
16,1,1,11,4,0,3939,1,3,1,3,1,1,40,3,2,2,2,1
17,1,2,18,2,3,3213,3,2,1,4,1,1,25,3,1,1,3,1
18,1,2,36,4,3,2337,1,5,4,3,1,1,36,3,2,1,3,1
19,1,4,11,4,0,7228,1,3,1,3,1,2,39,3,2,2,2,1
20,1,1,6,4,0,3676,1,3,1,3,1,1,37,3,1,3,3,1
21,1,2,12,4,0,3124,1,2,1,3,1,1,49,1,2,2,2,1
22,0,2,36,2,5,2384,1,2,4,3,1,4,33,3,1,1,2,1
23,1,2,12,4,4,1424,1,4,4,3,1,2,26,3,2,1,3,1
24,1,1,6,4,0,4716,5,2,1,3,1,1,44,3,2,2,2,1
25,1,2,11,3,3,4771,1,4,2,3,1,2,51,3,2,1,3,1
26,1,1,12,2,2,652,1,5,4,2,1,2,24,3,1,1,3,1
27,1,2,9,4,3,1154,1,5,2,3,1,1,37,3,2,3,2,1
28,1,4,15,2,0,3556,5,3,3,3,1,4,29,3,2,1,3,1
29,1,3,42,4,1,4796,1,5,4,3,1,4,56,3,3,1,3,1
30,1,3,30,4,3,3017,1,5,4,3,1,2,47,3,2,1,3,1
31,1,4,36,4,0,3535,1,4,4,3,1,3,37,3,2,2,3,1
32,1,4,36,4,0,6614,1,5,4,3,1,3,34,3,2,2,4,1
33,1,4,24,2,3,1376,3,4,4,2,1,3,28,3,2,1,3,1
34,1,1,15,2,0,1721,1,2,2,3,1,1,36,3,2,1,3,1
35,1,1,6,4,0,860,1,5,1,2,1,4,39,3,2,2,3,1
36,1,4,12,4,0,1495,1,5,4,3,1,1,38,3,2,2,2,1
37,1,4,12,4,3,1934,1,5,2,3,1,4,26,3,2,2,3,1
38,1,4,18,2,1,3378,5,3,2,3,1,2,31,3,2,1,3,1
39,1,4,24,4,1,3868,1,5,4,2,1,3,41,3,1,2,4,1
40,1,4,12,4,5,996,5,4,4,2,1,1,23,3,2,2,3,1
41,1,1,24,2,10,1755,1,5,4,2,3,1,58,3,2,1,2,1
42,1,4,18,4,0,1028,1,3,4,2,1,1,36,3,2,2,3,1
43,1,2,24,4,9,2825,5,4,4,3,1,4,34,3,2,2,3,1
44,1,2,18,2,6,1239,5,3,4,3,1,4,61,3,3,1,3,1
45,0,1,18,2,0,1216,1,2,4,2,1,3,23,3,1,1,3,1
46,1,4,24,2,9,1258,1,4,4,3,1,1,25,3,2,1,3,1
47,0,4,18,4,6,1864,2,3,4,2,1,1,30,3,2,2,3,1
48,1,4,24,2,0,1474,2,2,4,4,1,1,33,3,2,1,3,1
49,1,1,24,4,9,1382,2,4,4,3,1,1,26,3,2,2,3,1
50,1,4,12,2,0,640,1,3,4,1,1,1,49,3,2,1,2,1
51,1,3,36,2,3,3919,1,3,2,3,1,1,23,3,2,1,3,1
52,1,4,9,4,0,1224,1,3,3,3,1,1,30,3,2,2,3,1
53,1,4,12,4,3,2331,5,5,1,3,2,1,49,3,2,1,3,1
54,1,4,24,2,1,6313,5,5,3,3,1,3,41,3,2,1,4,1
55,1,1,12,4,3,385,1,4,4,2,1,1,58,3,2,4,2,1
56,1,4,12,4,3,1655,1,5,2,3,1,1,63,3,2,2,2,1
57,1,1,15,2,3,1053,1,2,4,4,1,1,27,3,2,1,3,2
58,1,4,21,2,3,3160,5,5,4,3,1,2,41,3,2,1,3,1
59,1,4,36,2,0,3079,5,3,4,3,1,1,36,3,2,1,3,1
60,1,4,12,4,0,1163,3,3,4,3,1,1,44,3,2,1,3,1
61,1,4,24,2,1,2679,1,2,4,2,1,4,29,3,2,1,4,1
62,1,4,48,4,3,3578,5,5,4,3,1,1,47,3,2,1,3,1
63,1,4,36,3,0,10875,1,5,2,3,1,3,45,3,2,2,3,1
64,1,1,12,3,0,1344,1,3,4,3,1,1,43,3,2,2,2,1
65,1,4,6,4,3,1237,2,3,1,2,1,2,27,3,2,2,3,1
66,1,4,12,2,3,3077,1,3,2,3,1,3,52,3,2,1,3,1
67,1,4,24,2,3,2284,1,4,4,3,1,3,28,3,2,1,3,1
68,1,2,12,2,3,1567,1,3,1,2,1,3,22,3,2,1,3,1
69,1,4,24,3,0,2032,1,5,4,3,1,4,60,3,3,2,3,1
70,1,2,21,4,2,2745,4,4,3,3,1,3,32,3,2,2,3,1
71,1,4,30,2,3,1867,5,5,4,3,1,3,58,3,2,1,3,1
72,1,4,36,2,3,2299,3,5,4,3,1,3,39,3,2,1,3,1
73,1,4,24,2,2,929,5,4,4,3,1,3,31,2,2,1,3,1
74,1,3,12,2,3,3399,5,5,2,3,1,3,37,3,2,1,4,1
75,1,2,9,2,2,2030,5,4,2,3,1,3,24,3,2,1,3,1
76,1,4,21,4,1,3275,1,5,1,3,1,3,36,3,2,1,4,1
77,1,4,24,4,0,1940,4,5,4,3,1,1,60,3,2,1,3,1
78,1,1,21,4,0,1602,1,5,4,4,1,3,30,3,2,2,3,1
79,1,4,15,2,3,1979,5,5,4,3,1,3,35,3,2,1,3,1
80,1,4,24,4,0,2022,1,3,4,2,1,3,37,3,2,1,3,1
81,1,4,36,4,3,3342,5,5,4,3,1,3,51,3,2,1,3,1
82,1,2,18,2,0,5866,2,3,2,3,1,3,30,3,2,2,3,1
83,1,3,15,4,1,2360,3,3,2,3,1,3,36,3,2,1,3,1
84,1,4,15,4,2,1520,5,5,4,3,1,2,63,3,2,1,3,1
85,1,1,12,2,0,3651,4,3,1,3,1,2,31,3,2,1,3,1
86,1,4,24,4,1,2346,1,4,4,3,1,3,35,3,2,2,3,1
87,1,4,36,3,3,4454,1,3,4,2,1,1,34,3,2,2,3,1
88,1,1,6,4,0,666,4,4,3,2,1,1,39,3,2,2,2,1
89,1,2,24,3,0,1965,5,3,4,2,1,3,42,3,1,2,3,1
90,1,2,12,4,0,1995,2,2,4,3,1,3,27,3,2,1,3,1
91,1,2,30,2,3,2991,5,5,2,2,1,3,25,3,2,1,3,1
92,1,2,30,0,9,4221,1,3,2,2,1,3,28,3,2,2,3,1
93,1,1,9,2,3,1364,1,4,3,3,1,1,59,3,2,1,3,1
94,1,2,18,4,2,6361,1,5,2,3,1,4,41,3,2,1,3,1
95,1,4,27,4,2,4526,4,2,4,3,1,1,32,2,2,2,2,1
96,1,2,12,4,3,3573,1,3,1,2,1,1,23,3,2,1,2,1
97,0,2,36,3,9,4455,1,3,2,1,1,1,30,2,2,2,4,1
98,1,1,9,2,2,2136,1,3,3,3,1,1,25,3,2,1,3,1
99,1,2,42,4,9,5954,1,4,2,2,1,1,41,1,2,2,2,1
100,1,4,24,4,2,3777,4,3,4,3,1,1,40,3,2,1,3,1
101,1,1,15,2,9,806,1,3,4,2,1,2,22,3,2,1,2,1
102,1,2,24,3,9,4712,5,3,4,3,1,2,34,1,2,2,4,1
103,1,2,36,3,0,7432,1,3,2,2,1,2,54,3,1,1,3,1
104,1,4,24,4,3,1851,1,4,4,4,3,3,33,3,2,2,3,1
105,1,4,24,2,0,1393,1,3,2,3,3,1,31,3,2,1,3,1
106,1,4,12,4,9,1412,1,3,4,2,3,1,29,3,2,2,4,1
107,1,4,18,2,3,1473,1,2,3,4,1,1,39,3,2,1,3,1
108,1,4,24,2,3,1533,1,2,4,2,1,3,38,2,2,1,3,1
109,1,4,12,4,6,2012,5,4,4,2,1,3,61,3,2,1,3,1
110,0,1,15,2,0,3959,1,3,3,2,1,2,29,3,2,1,3,1
111,1,1,6,2,2,428,1,5,2,2,1,2,49,1,2,1,3,1
112,1,2,12,4,0,2366,3,4,3,1,1,3,36,3,2,1,4,1
113,1,4,12,2,2,763,1,3,4,2,1,1,26,3,2,1,3,1
114,1,2,21,2,2,3976,5,4,2,3,1,3,35,3,2,1,3,1
115,1,2,18,2,0,6260,1,4,3,3,1,1,28,3,1,1,2,1
116,1,2,9,4,2,1919,1,4,4,3,1,3,35,3,1,1,3,1
117,1,4,24,2,1,2603,4,3,2,2,1,3,28,3,1,1,3,1
118,1,4,9,4,6,936,3,5,4,3,1,3,52,3,2,2,3,1
119,1,4,24,2,2,3062,3,5,4,3,1,4,32,3,1,1,3,1
120,1,2,36,2,3,4795,1,2,4,2,1,4,30,3,2,1,4,1
121,1,4,36,4,1,5842,1,5,2,3,1,2,35,3,2,2,3,1
122,1,2,6,2,3,2063,1,2,4,4,1,3,30,3,1,1,4,1
123,1,4,15,4,3,1459,1,3,4,2,1,3,43,3,2,1,2,1
124,1,4,15,2,3,1213,3,5,4,3,1,2,47,2,2,1,3,1
125,1,4,24,4,3,5103,1,2,3,4,1,4,47,3,3,3,3,1
126,1,4,15,2,4,874,5,2,4,2,1,1,24,3,2,1,3,1
127,1,4,6,2,2,2978,3,3,1,3,1,3,32,3,2,1,3,1
128,1,4,18,2,0,1820,1,3,2,4,1,2,30,3,2,1,4,1
129,1,4,24,4,3,2872,2,5,3,3,1,1,36,3,2,1,3,1
130,1,3,24,2,2,1925,1,3,2,3,1,1,26,3,2,1,3,1
131,1,4,18,2,2,2515,1,3,3,3,1,1,43,3,2,1,3,1
132,1,3,6,2,2,2116,1,3,2,3,1,1,41,3,2,1,3,1
133,1,4,18,2,3,1453,1,2,3,2,1,1,26,3,2,1,3,1
134,1,4,10,2,0,1364,1,3,2,2,1,3,64,3,2,1,3,1
135,1,4,6,2,2,1543,4,3,4,1,1,1,33,3,2,1,3,1
136,1,2,12,2,0,1318,4,5,4,3,1,1,54,3,2,1,3,1
137,1,1,24,1,0,2325,2,4,2,3,1,3,32,1,2,1,3,1
138,1,2,6,4,8,932,5,4,1,2,1,2,39,3,2,2,2,1
139,1,3,24,4,3,3148,5,3,3,3,1,3,31,3,2,2,3,1
140,1,4,36,2,3,3835,5,5,2,2,1,1,45,3,2,1,2,1
141,1,4,9,2,6,3832,5,5,1,3,1,1,64,3,2,1,2,1
142,1,2,24,2,3,5084,5,5,2,2,1,3,42,3,2,1,3,1
143,1,4,9,4,2,2406,1,1,2,3,1,3,31,3,2,1,4,1
144,1,4,36,2,3,2394,5,3,4,2,1,3,25,3,2,1,3,1
145,1,4,21,2,1,2476,5,5,4,3,1,1,46,3,2,1,4,1
146,1,1,24,2,1,2964,5,5,4,3,1,4,49,1,3,1,3,1
147,1,1,12,2,2,1262,5,5,2,1,1,2,49,3,2,1,2,1
148,1,4,12,2,9,1542,1,4,2,3,1,3,36,3,2,1,3,1
149,1,2,24,4,3,1743,1,5,4,3,1,2,48,3,2,2,2,1
150,1,3,12,1,3,409,4,3,3,2,1,1,42,3,1,2,3,1
151,1,4,12,2,3,2171,1,2,2,2,1,3,29,1,2,1,3,1
152,1,4,48,4,1,8858,5,4,2,3,1,4,35,3,3,2,3,1
153,1,2,24,2,0,3512,2,4,2,3,1,3,38,1,2,2,3,1
154,1,2,12,2,3,1158,3,3,3,1,1,3,26,3,2,1,3,1
155,1,4,24,4,3,2684,1,3,4,3,1,1,35,3,2,2,2,1
156,1,1,12,2,3,1498,1,3,4,2,1,3,23,1,2,1,3,1
157,1,4,30,4,3,5954,1,4,3,3,2,3,38,3,2,1,3,1
158,0,2,48,1,9,6416,1,5,4,2,1,4,59,3,1,1,3,1
159,1,2,12,4,2,3617,1,5,1,3,1,3,28,3,1,3,3,1
160,1,4,12,4,3,1291,1,3,4,2,1,2,35,3,2,2,3,1
161,1,3,24,4,9,1275,4,3,2,1,1,1,36,3,2,2,3,1
162,1,4,24,2,2,3972,1,4,2,2,1,2,25,3,1,1,3,1
163,1,4,15,4,2,3343,1,3,4,3,1,4,28,3,3,1,3,1
164,1,3,15,2,6,392,1,2,4,2,1,2,23,3,1,1,3,1
165,1,4,9,4,0,2134,1,3,4,3,1,3,48,3,2,3,3,1
166,1,4,30,4,3,5771,1,4,4,2,1,3,25,3,2,2,3,1
167,1,4,24,4,9,4526,1,3,3,3,1,1,74,3,2,1,4,1
168,1,4,15,4,2,2788,1,4,2,2,2,3,24,1,2,2,3,1
169,1,4,6,4,3,1382,1,3,1,2,1,3,28,3,2,2,3,1
170,1,3,36,2,3,5848,1,3,4,3,1,3,24,3,2,1,3,1
171,0,1,12,2,0,1228,1,3,4,2,1,1,24,3,2,1,2,1
172,1,3,12,2,3,1297,1,3,3,4,1,1,23,3,1,1,3,1
173,1,4,24,2,3,1552,1,4,3,3,1,3,32,1,2,1,3,1
174,1,4,12,2,3,1963,1,4,4,3,1,3,31,3,1,2,4,1
175,1,4,24,2,3,3235,3,5,3,1,1,3,36,3,2,1,4,1
176,1,4,24,4,9,4139,2,3,3,3,1,2,27,3,2,2,2,1
177,1,2,12,4,1,1804,2,2,3,3,1,2,44,3,2,1,3,1
178,1,4,18,2,9,1950,1,4,4,3,1,3,34,2,2,2,3,1
179,1,4,48,3,3,12749,3,4,4,3,1,3,37,3,2,1,4,1
180,1,4,9,2,4,1236,1,2,1,2,1,1,23,3,1,1,3,1
181,1,4,18,4,0,1055,1,2,4,2,1,2,30,3,2,2,3,1
182,1,1,30,0,9,8072,5,2,2,3,1,3,25,1,2,3,3,1
183,1,4,30,4,3,2831,1,3,4,2,1,3,33,3,2,1,3,1
184,1,4,9,2,9,1449,1,4,3,2,1,3,27,3,2,2,3,1
185,1,4,36,2,9,5742,2,4,2,3,1,3,31,3,2,2,3,1
186,1,4,12,2,0,2390,5,5,4,3,1,3,50,3,2,1,3,1
187,1,4,24,2,3,3430,3,5,3,3,1,3,31,3,2,1,3,1
188,1,2,36,2,6,2273,1,4,3,3,1,3,32,3,2,2,3,1
189,1,3,21,2,0,2923,2,3,1,2,1,3,28,1,2,1,4,1
190,1,4,24,2,3,1901,2,3,4,3,1,3,29,3,1,1,4,1
191,1,2,36,2,6,3711,5,3,2,4,1,3,27,3,2,1,3,1
192,1,2,48,2,0,8487,5,4,1,2,1,3,24,3,2,1,3,1
193,1,4,24,2,0,2255,5,2,4,3,1,2,54,3,2,1,3,1
194,1,4,12,2,3,1262,1,3,3,3,1,3,25,3,2,1,3,1
195,1,4,33,4,1,7253,1,4,3,3,1,3,35,3,2,2,4,1
196,1,4,6,4,0,6761,1,4,1,3,1,4,45,3,2,2,4,1
197,1,4,18,4,2,1817,1,3,4,2,1,4,28,3,2,2,3,1
198,1,4,12,2,3,2141,2,4,3,3,1,4,35,3,2,1,3,1
199,1,4,48,1,9,3609,1,3,1,2,1,1,27,2,2,1,3,1
200,1,4,30,2,3,2333,3,5,4,3,1,3,30,1,2,1,4,1
201,1,4,28,1,1,7824,5,2,3,3,3,1,40,1,1,2,3,1
202,1,3,18,1,3,1445,5,4,4,3,1,3,49,1,2,1,2,1
203,1,1,24,2,2,7721,5,2,1,2,1,2,30,3,2,1,3,2
204,1,1,21,2,0,3763,5,4,2,3,2,1,24,3,2,1,2,2
205,1,2,18,2,9,4439,1,5,1,3,2,1,33,1,2,1,4,1
206,1,1,12,2,3,1107,1,3,2,3,1,1,20,3,1,1,4,1
207,1,2,15,2,3,1444,5,2,4,3,1,2,23,3,2,1,3,1
208,1,2,48,1,0,12169,5,1,4,3,2,4,36,3,3,1,4,1
209,1,4,9,2,3,2753,2,5,3,3,2,3,35,3,2,1,3,1
210,1,3,4,2,0,1494,5,2,1,3,1,1,29,3,2,1,2,2
211,1,1,24,1,2,2828,3,3,4,3,1,1,22,2,2,1,3,1
212,1,1,24,1,2,2483,3,3,4,3,1,1,22,2,2,1,3,1
213,1,3,6,4,0,1299,1,3,1,3,1,1,74,3,2,3,1,2
214,1,2,9,2,0,1549,5,2,4,3,1,1,35,3,2,1,1,1
215,1,3,10,2,0,3949,1,2,1,3,3,2,37,3,2,1,2,1
216,1,4,10,2,1,2901,5,2,1,2,1,1,31,3,1,1,3,1
217,1,3,6,2,0,709,4,2,2,4,1,1,27,3,2,1,1,2
218,1,1,47,2,0,10722,1,2,1,2,1,1,35,3,2,1,2,1
219,1,4,10,2,0,1287,5,5,4,3,2,2,45,3,2,1,2,2
220,1,1,18,1,3,1940,1,2,3,3,2,4,36,1,3,1,4,1
221,1,3,30,4,3,3656,5,5,4,3,1,2,49,2,2,2,2,1
222,1,4,24,3,1,4679,1,4,3,3,1,3,35,3,2,2,2,1
223,1,4,27,3,1,8613,4,3,2,3,1,3,27,3,2,2,3,1
224,1,1,18,2,2,2659,4,3,4,3,1,3,28,3,2,1,3,1
225,1,4,24,4,3,1516,4,3,4,2,1,1,43,3,2,2,2,1
226,1,1,18,2,0,4380,2,3,3,3,1,3,35,3,2,1,2,1
227,1,4,14,3,0,802,1,3,4,3,1,3,27,3,2,2,2,1
228,1,4,21,2,9,1572,4,5,4,2,1,1,36,1,2,1,2,1
229,1,2,48,1,9,3566,2,4,4,3,1,3,30,3,2,1,3,1
230,1,4,24,2,3,1278,1,5,4,3,1,1,36,3,2,1,4,1
231,1,4,6,0,3,426,1,5,4,4,1,3,39,3,2,1,2,1
232,1,4,39,2,1,8588,2,5,4,3,1,3,45,3,2,1,4,1
233,1,1,30,2,1,3857,1,3,4,1,1,2,40,3,2,1,4,1
234,0,2,12,2,0,685,1,4,2,4,1,3,25,1,2,1,2,1
235,1,1,24,2,3,1603,1,5,4,2,1,3,55,3,2,1,3,1
236,1,4,21,2,2,2241,1,5,4,3,1,1,50,3,2,2,3,1
237,1,1,24,2,3,2384,1,5,4,3,1,1,64,1,1,1,2,1
238,1,4,4,2,2,601,1,2,1,2,1,1,23,3,1,1,2,1
239,1,4,39,2,1,2569,3,3,4,3,1,3,24,3,2,1,3,1
240,1,4,15,4,3,1316,3,3,2,4,1,2,47,3,2,2,2,1
241,1,4,60,2,0,10366,1,5,2,3,1,2,42,3,2,1,4,1
242,1,4,18,2,9,1568,2,3,3,2,1,2,24,3,1,1,2,1
243,1,4,18,4,3,629,3,5,4,3,1,2,32,1,2,2,4,1
244,1,4,6,1,3,1750,3,5,2,3,1,2,45,1,2,1,2,1
245,1,4,24,2,1,3488,2,4,3,2,1,3,23,3,2,1,3,1
246,1,4,18,4,3,1800,1,3,4,3,1,3,24,3,2,2,3,1
247,1,4,24,3,2,4151,2,3,2,3,1,2,35,3,2,2,3,1
248,1,2,15,2,5,2631,2,3,3,2,1,1,25,3,2,1,2,1
249,1,4,21,2,1,5248,5,3,1,3,1,3,26,3,2,1,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,1,2,36,3,0,2862,2,5,4,3,1,4,30,3,3,1,3,1
751,0,1,9,2,0,654,1,3,4,3,1,3,28,3,2,1,2,1
752,0,2,9,4,6,1136,4,5,4,3,1,4,32,3,3,2,3,1
753,0,2,24,2,1,4113,3,2,3,2,1,3,28,3,1,1,3,1
754,0,2,6,2,0,14555,5,1,1,3,1,2,23,3,2,1,1,1
755,0,1,15,0,0,950,1,5,4,3,1,3,33,3,1,2,3,1
756,0,1,24,4,0,1199,1,5,4,3,1,3,60,3,2,2,2,1
757,0,1,12,0,0,1082,1,3,4,3,1,3,48,1,2,2,3,1
758,0,2,30,2,0,2150,1,3,4,2,3,4,24,1,2,1,3,1
759,0,2,36,4,0,2820,1,2,4,1,1,3,27,3,2,2,3,1
760,0,2,48,2,3,3060,1,4,4,3,1,1,28,3,2,2,3,1
761,0,1,18,2,3,2600,1,3,4,3,1,4,65,3,3,2,3,1
762,0,4,21,0,0,5003,5,3,1,2,1,2,29,1,2,2,3,1
763,0,2,60,2,6,6288,1,3,4,3,1,4,42,3,3,1,3,1
764,0,4,24,3,0,2538,1,5,4,3,1,3,47,3,2,2,2,1
765,0,4,9,2,3,1478,1,4,4,3,1,3,22,3,2,1,3,1
766,0,2,39,4,3,4933,1,4,2,3,3,1,25,3,2,2,3,1
767,0,4,18,4,0,1530,1,3,3,3,1,2,32,1,2,2,3,1
768,0,2,9,1,0,1437,2,4,2,3,1,4,29,3,2,1,3,1
769,0,1,15,2,4,1275,5,3,4,2,1,3,24,3,1,1,3,1
770,0,1,24,2,3,1823,1,1,4,3,1,3,30,2,2,1,4,1
771,0,1,9,2,0,1422,1,2,3,3,1,4,27,3,3,1,4,1
772,0,1,18,2,4,1217,1,3,4,4,1,1,47,3,2,1,2,1
773,0,1,36,2,0,9271,1,4,2,3,1,3,24,3,2,1,3,1
774,0,1,36,3,9,2145,1,4,2,3,1,3,24,3,2,2,3,1
775,0,1,36,2,0,1842,1,2,4,2,1,3,34,3,2,1,3,1
776,0,2,18,3,2,4297,1,5,4,1,1,4,40,3,2,1,4,1
777,0,1,6,4,2,3384,1,3,1,1,1,1,44,3,1,1,4,1
778,0,2,18,4,3,1245,1,3,4,4,1,3,33,3,2,1,3,1
779,0,4,15,2,6,4623,2,3,3,3,1,2,40,3,2,1,4,1
780,0,2,30,4,2,8386,1,4,2,3,1,2,49,3,2,1,3,1
781,0,1,24,3,3,1024,1,2,4,4,1,1,48,2,2,1,3,1
782,0,2,36,2,0,14318,1,5,4,3,1,4,57,3,3,1,4,1
783,0,2,6,1,6,433,4,2,4,2,1,2,24,1,1,1,3,1
784,0,1,12,1,3,2149,1,3,4,1,1,4,29,3,3,1,3,1
785,0,4,24,2,3,2397,3,5,3,3,1,3,35,1,2,2,3,1
786,0,2,6,1,0,931,2,2,1,2,1,2,32,2,2,1,2,1
787,0,2,15,3,5,1512,4,3,3,4,1,2,61,2,2,2,3,1
788,0,2,24,0,9,4241,1,3,1,3,1,1,36,3,2,3,2,1
789,0,2,24,4,2,4736,1,2,2,2,1,3,25,1,2,1,2,1
790,0,2,15,0,0,1778,1,2,2,2,1,1,26,3,1,2,1,1
791,0,3,15,2,3,2327,1,2,2,2,1,1,25,3,2,1,2,1
792,0,1,24,1,2,6872,1,2,2,1,1,2,55,1,2,1,3,1
793,0,1,12,2,6,795,1,2,4,2,1,2,53,3,2,1,3,1
794,0,3,30,3,9,1908,1,5,4,3,1,1,66,3,2,1,4,1
795,0,2,36,0,9,1953,1,5,4,3,1,4,61,3,3,1,4,1
796,0,3,18,2,2,2864,1,3,2,3,1,1,34,3,2,1,2,1
797,0,3,21,4,6,2319,1,2,2,1,1,3,33,3,1,1,3,1
798,0,1,24,2,0,915,5,5,4,2,1,3,29,1,2,1,3,1
799,0,3,24,2,0,947,1,4,4,3,1,4,38,1,3,1,3,1
800,0,1,24,2,0,1381,5,3,4,2,1,2,35,3,2,1,3,1
801,0,1,24,2,0,1285,5,4,4,2,1,4,32,3,1,1,3,1
802,0,1,24,2,0,1371,5,3,4,2,1,1,25,3,1,1,3,1
803,0,2,18,2,0,1042,5,3,4,2,1,2,33,3,2,1,3,1
804,0,1,12,2,0,900,5,3,4,4,1,3,23,3,2,1,3,1
805,0,1,24,2,0,1207,1,2,4,2,1,2,24,3,1,1,3,1
806,0,2,18,0,0,2278,2,2,3,2,1,3,28,3,2,2,3,1
807,0,1,60,3,9,6836,1,5,3,3,1,4,63,3,2,2,3,1
808,0,1,24,2,2,3345,1,5,4,3,1,2,39,3,1,1,4,1
809,0,1,6,1,6,1198,1,5,4,2,1,4,35,3,3,1,3,1
810,0,2,48,2,9,15672,1,3,2,3,1,3,23,3,2,1,3,1
811,0,1,60,2,9,7297,1,5,4,3,2,4,36,3,1,1,3,1
812,0,4,18,2,5,1943,1,2,4,2,1,1,23,3,2,1,3,1
813,0,1,18,2,3,3190,1,3,2,2,1,1,24,3,2,1,3,1
814,0,2,9,1,1,5129,1,5,2,2,1,4,74,1,3,1,4,1
815,0,4,18,3,2,1808,1,4,4,2,1,1,22,3,2,1,3,1
816,0,3,10,2,0,1240,2,5,1,2,1,4,48,3,3,1,2,1
817,0,1,12,2,0,759,1,4,4,3,1,1,26,3,2,1,3,1
818,0,2,8,2,2,1237,1,3,3,2,1,1,24,3,2,1,3,1
819,0,4,9,2,2,1980,1,2,2,2,2,3,19,3,1,2,3,1
820,0,2,48,2,3,10961,4,4,1,3,2,4,27,1,2,2,3,1
821,0,1,36,3,6,6887,1,3,4,3,1,2,29,2,2,1,3,1
822,0,1,24,2,3,1938,1,2,4,1,1,2,32,3,2,1,3,1
823,0,1,21,2,3,1835,1,3,3,2,1,1,25,3,2,2,3,1
824,0,1,24,3,3,1659,1,2,4,2,1,3,29,3,1,1,2,1
825,0,2,6,3,0,1209,1,1,4,3,1,2,47,3,2,1,4,1
826,0,2,48,0,9,3844,2,4,4,3,1,4,34,3,3,1,2,1
827,0,1,12,4,0,4843,1,5,3,3,2,2,43,3,1,2,3,1
828,0,2,12,2,5,639,1,3,4,3,1,3,30,3,2,1,3,1
829,0,2,48,2,3,5951,1,3,2,2,1,1,22,3,2,1,3,1
830,0,2,36,0,3,3804,1,3,4,2,1,3,42,3,2,1,3,1
831,0,4,36,3,3,4463,1,3,4,3,1,3,26,3,2,2,4,1
832,0,4,36,3,9,7980,5,2,4,3,1,3,27,3,1,2,3,1
833,0,3,36,2,3,4210,1,3,4,3,1,3,26,3,2,1,3,1
834,0,4,6,2,2,4611,1,2,1,2,1,2,32,3,2,1,3,1
835,0,2,24,2,1,11560,1,3,1,2,1,3,23,3,1,2,4,1
836,0,4,18,0,9,4165,1,3,2,3,1,3,36,2,2,2,3,1
837,0,2,24,2,2,4057,1,4,3,1,1,3,43,3,2,1,3,1
838,0,4,18,1,0,6458,1,5,2,3,1,4,39,1,2,2,4,1
839,0,4,12,2,0,1386,3,3,2,2,1,2,26,3,2,1,3,1
840,0,1,36,2,6,1977,5,5,4,3,1,4,40,3,2,1,4,1
841,0,2,18,4,2,1928,1,2,2,3,1,1,31,3,2,2,2,1
842,0,4,12,2,2,1123,3,3,4,2,1,3,29,3,1,1,2,1
843,0,2,24,2,10,11328,1,3,2,3,2,3,29,1,2,2,4,1
844,0,2,24,4,10,11938,1,3,2,3,2,3,39,3,2,2,4,1
845,0,2,27,4,3,2520,3,3,4,3,1,2,23,3,2,2,2,1
846,0,2,30,3,3,1919,2,2,4,3,1,4,30,2,2,2,4,1
847,0,2,60,1,10,14782,2,5,3,2,1,4,60,1,3,2,4,1
848,0,2,36,2,3,2671,2,3,4,2,2,4,50,3,3,1,3,1
849,0,2,36,2,6,12612,2,3,1,3,1,4,47,3,3,1,3,1
850,0,2,45,2,3,3031,2,3,4,3,3,2,21,3,1,1,3,1
851,0,1,12,1,3,626,1,3,4,2,1,1,24,1,2,1,2,1
852,0,2,24,4,9,1935,1,5,4,1,1,1,31,3,2,2,3,1
853,0,3,24,4,0,1344,5,4,4,3,1,1,37,1,2,2,2,1
854,0,4,18,2,2,1533,1,2,4,4,2,2,43,3,2,1,2,1
855,0,1,48,2,0,3931,1,4,4,3,1,4,46,3,3,1,3,1
856,0,1,24,1,2,3349,3,2,4,3,1,4,30,3,3,1,3,1
857,0,1,36,2,3,2302,1,3,4,1,1,3,31,3,1,1,3,1
858,0,1,42,2,3,3965,1,2,4,3,1,3,34,3,2,1,3,1
859,0,1,12,2,3,727,2,2,4,4,1,4,33,3,2,1,2,1
860,0,4,48,2,9,3914,5,3,4,1,1,1,38,1,2,1,3,1
861,0,1,48,2,9,4308,1,2,3,2,1,2,24,3,1,1,3,1
862,0,2,12,2,3,1534,1,2,1,4,1,1,23,3,1,1,3,1
863,0,4,18,4,0,2775,1,4,2,3,1,2,31,1,2,2,3,1
864,0,1,40,4,6,5998,1,3,4,3,1,4,27,1,2,1,3,1
865,0,3,15,4,3,1271,5,3,3,3,1,4,39,3,3,2,3,1
866,0,2,12,2,0,1295,1,2,3,2,1,3,25,3,1,1,3,1
867,0,2,36,2,1,9398,1,2,1,4,1,3,28,3,1,1,4,1
868,0,2,12,2,2,951,2,2,4,2,1,3,27,1,1,4,3,1
869,0,2,24,2,0,1355,1,2,3,2,1,3,25,3,2,1,2,1
870,0,1,48,2,4,3051,1,3,3,3,1,3,54,3,2,1,3,1
871,0,4,36,4,0,7855,1,3,4,2,1,1,25,2,2,2,3,1
872,0,4,18,2,3,433,1,1,3,2,2,1,22,3,1,1,3,1
873,0,4,36,3,9,9572,1,2,1,1,1,3,28,3,2,2,3,1
874,0,2,24,1,6,1837,1,4,4,2,1,4,34,1,3,1,2,1
875,0,2,30,4,0,4249,1,1,4,4,1,3,28,3,2,2,4,1
876,0,2,30,4,0,5234,1,1,4,4,1,3,28,3,2,2,4,1
877,0,1,48,2,3,6758,1,3,3,2,1,3,31,3,2,1,3,1
878,0,1,9,2,3,1366,1,2,3,2,1,2,22,3,1,1,3,1
879,0,1,24,1,10,1358,5,5,4,3,1,3,40,2,2,1,4,1
880,0,1,18,2,2,2473,1,1,4,3,1,3,25,3,2,1,1,1
881,0,3,9,0,3,1337,1,2,4,3,1,3,34,3,2,2,4,1
882,0,1,48,2,0,7763,1,5,4,3,1,4,42,1,3,1,4,1
883,0,2,15,1,0,1264,2,3,2,4,1,2,25,3,1,1,3,1
884,0,2,15,2,0,2631,2,3,2,2,1,3,28,3,1,2,3,1
885,0,2,48,2,0,6560,2,4,3,3,1,2,24,3,2,1,3,1
886,0,1,24,2,0,3123,1,2,4,2,1,2,27,3,2,1,3,1
887,0,1,36,4,6,8065,1,3,3,2,1,4,25,3,2,2,4,1
888,0,1,24,2,3,2439,1,2,4,2,1,1,35,3,2,1,3,1
889,0,2,36,2,2,9034,2,2,4,3,2,4,29,3,1,1,4,1
890,0,2,60,2,0,14027,1,4,4,3,1,4,27,3,2,1,4,1
891,0,1,36,4,1,9629,1,4,4,3,1,3,24,3,2,2,3,1
892,0,2,12,2,3,1484,5,3,2,4,1,1,25,3,2,1,3,1
893,0,1,18,2,2,1131,1,1,4,2,1,3,33,3,2,1,3,1
894,0,2,24,3,2,2064,1,1,3,2,1,2,34,3,2,1,4,1
895,0,2,18,2,1,12976,1,1,3,2,1,4,38,3,3,1,4,1
896,0,4,21,3,9,2580,3,2,4,3,1,1,41,1,2,1,2,1
897,0,4,27,2,0,2570,1,3,3,2,1,1,21,3,1,1,3,1
898,0,2,27,2,9,3915,1,3,4,3,1,3,36,3,2,1,3,1
899,0,4,10,2,0,1309,5,3,4,3,3,2,27,3,2,1,2,1
900,0,1,24,2,0,4817,1,4,2,3,2,2,31,3,2,1,3,1
901,0,1,12,2,0,2579,1,2,4,3,1,1,33,3,2,1,2,1
902,0,2,36,3,0,2225,1,5,4,3,1,4,57,1,3,2,3,1
903,0,1,18,2,2,4153,1,3,2,3,2,3,42,3,2,1,3,1
904,0,1,18,0,2,3114,1,2,1,2,1,2,26,3,1,1,3,1
905,0,1,18,4,2,2124,1,3,4,2,1,1,24,3,1,2,3,1
906,0,1,18,1,2,1553,1,3,4,3,1,3,44,1,2,1,3,1
907,0,1,30,2,2,2406,1,4,4,2,1,1,23,3,1,1,3,1
908,0,1,24,3,0,1333,1,1,4,3,1,1,43,3,3,2,3,1
909,0,1,48,0,2,7119,1,3,3,3,1,4,53,3,3,2,3,1
910,0,1,24,3,0,4870,1,3,3,3,1,4,53,3,3,2,3,1
911,0,1,12,4,0,691,1,5,4,3,1,2,35,3,2,2,3,1
912,0,1,42,3,3,4370,1,4,3,3,1,2,26,1,2,2,3,1
913,0,1,36,1,2,2746,1,5,4,3,1,3,31,1,2,1,3,1
914,0,1,24,0,2,4110,1,5,3,3,1,4,23,1,1,2,3,1
915,0,1,18,2,2,2462,1,3,2,3,1,3,22,3,2,1,3,1
916,0,1,12,2,2,1282,1,3,2,2,1,3,20,3,1,1,3,1
917,0,2,12,0,2,2969,1,2,4,2,1,2,25,3,1,2,3,1
918,0,1,48,0,1,4605,1,5,3,3,1,4,24,3,3,2,3,1
919,0,1,48,4,1,6331,1,5,4,3,1,4,46,3,3,2,3,1
920,0,1,24,1,2,3552,1,4,3,3,1,3,27,1,2,1,3,1
921,0,1,12,1,0,697,1,2,4,3,1,3,46,1,2,2,3,1
922,0,1,24,2,0,1442,1,4,4,2,1,3,23,3,1,2,3,1
923,0,1,27,0,9,5293,1,1,2,3,1,2,50,3,2,2,3,1
924,0,1,21,3,6,3414,1,2,2,3,1,2,26,2,2,2,3,1
925,0,1,18,2,2,2039,1,3,1,2,1,1,20,3,1,1,3,1
926,0,1,24,1,9,3161,1,3,4,3,1,2,31,1,1,1,3,1
927,0,1,12,2,8,902,1,4,4,4,1,2,21,3,1,1,3,1
928,0,1,48,2,1,10297,1,4,4,3,1,4,39,3,3,3,3,1
929,0,2,48,0,9,14421,1,3,2,3,1,3,25,2,2,1,3,1
930,0,2,18,4,0,1056,1,5,3,3,3,1,30,3,2,2,3,1
931,0,1,12,2,0,1274,1,2,3,2,1,1,37,1,2,1,2,1
932,0,2,12,2,0,1223,1,5,1,1,1,1,46,3,1,2,3,1
933,0,1,12,2,0,1372,1,4,2,1,1,3,36,3,2,1,3,1
934,0,1,16,4,0,2625,1,5,2,3,3,2,43,3,1,1,3,2
935,0,1,20,4,0,2235,1,3,4,4,3,2,33,1,1,2,3,2
936,0,2,9,2,2,959,1,3,1,2,1,3,29,1,2,1,3,1
937,0,2,18,4,0,884,1,5,4,3,1,3,36,3,2,1,3,1
938,0,2,24,2,0,1246,1,2,4,3,1,1,23,1,2,1,2,1

### Since the Count of positive and negative samples are not balanced we are going to split the dataset to train and test for both postive and negative creditabilities and then concat them together to obtain the final train and test datasets.

In [563]:
cred1_df = datasetNew[datasetNew['Creditability']==1]
cred0_df = datasetNew[datasetNew['Creditability']==0]

In [564]:
# Now we are splitting cred1_df and cred0_df using train_test_split from sklearn
from sklearn.model_selection import train_test_split

X1_attributes = cred1_df.iloc[:,1:]
X2_attributes = cred0_df.iloc[:,1:]

y1_label = cred1_df.iloc[:,0]
y2_label = cred0_df.iloc[:,0]

X1_train, X1_test, y1_train, y1_test = train_test_split(X1_attributes, y1_label, test_size = 0.20, random_state = 0)
X2_train, X2_test, y2_train, y2_test = train_test_split(X2_attributes, y2_label, test_size = 0.20, random_state = 0)

In [565]:
# Noe we concat the train and test split df's from above
X_train = pd.concat([X1_train, X2_train], axis=0)
X_test = pd.concat([X1_test, X2_test], axis=0)
y_train = pd.concat([y1_train, y2_train], axis=0)
y_test = pd.concat([y1_test, y2_test], axis=0)

## Using Naive Bayes Classifier

In [566]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [567]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [568]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 39,  21],
       [ 30, 110]])

In [569]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.745

In [570]:
score=pd.DataFrame(list(metrics.precision_recall_fscore_support(y_test,y_pred)),index=['Precision','Recall','F1-Score','Support']).T

In [571]:
score

   Precision    Recall  F1-Score  Support
0   0.565217  0.650000  0.604651     60.0
1   0.839695  0.785714  0.811808    140.0

### Using Decison Tree Classifier

In [572]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifierDT = DecisionTreeClassifier(random_state = 2)
classifierDT.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=2,
            splitter='best')

In [573]:
# Predicting the Test set results
y_pred = classifierDT.predict(X_test)

In [574]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 31,  29],
       [ 26, 114]])

In [575]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.725

In [576]:
score=pd.DataFrame(list(metrics.precision_recall_fscore_support(y_test,y_pred)),index=['Precision','Recall','F1-Score','Support']).T

In [578]:
score

   Precision    Recall  F1-Score  Support
0   0.543860  0.516667  0.529915     60.0
1   0.797203  0.814286  0.805654    140.0

### Using Random Forest Classifier

In [579]:
#### Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifierRF = RandomForestClassifier(n_estimators = 350, max_depth=140, random_state = 89)
classifierRF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=140, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=350, n_jobs=None,
            oob_score=False, random_state=89, verbose=0, warm_start=False)

In [580]:
# Predicting the Test set results
y_pred = classifierRF.predict(X_test)

In [581]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 37,  23],
       [ 12, 128]])

In [582]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.825

In [583]:
score=pd.DataFrame(list(metrics.precision_recall_fscore_support(y_test,y_pred)),index=['Precision','Recall','F1-Score','Support']).T

In [561]:
score

   Precision    Recall  F1-Score  Support
0   0.755102  0.616667  0.678899     60.0
1   0.847682  0.914286  0.879725    140.0